name: Build and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: darwin
            goarch: amd64

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: go build -v -o sanitizetelebot-${{ matrix.goos }}-${{ matrix.goarch }} sanitizetelebot.go
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sanitizetelebot-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ./sanitizetelebot-${{ matrix.goos }}-${{ matrix.goarch }}
